# Nixpacks configuration for Laravel with Vite

[phases.setup]
nixPkgs = ["nodejs_20", "php83", "php83Packages.composer"]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan storage:link && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
